### ISSUE TITLE
still some bug in python 3.8

### ISSUE THREAD

**Issue by huineng** [sundarnagarajan/python_protected_class#3]
thanks for fixing the code to work with python 3.8
i though face another problem when i run the example

error 
```
ImportError: cannot import name 'Protected' from 'protected_class' (/usr/local/lib/python3.8/site-packages/protected_class.cpython-38-x86_64-linux-gnu.so)
```

on the other side some functions can be import but i'm trying to understand how this works

```
class MyClass(object):
    def __init__(self):
        self.__hidden = 1
        self._private = 2
        self.public = 3


# Get an instance of your class
myinst = MyClass()

# import + ONE line to wrap and protect class attributes
from protected_class import protect
wrapped = protect(myinst, hide_data = True,hide_all = True , hide_dunder = True, hide_private = True)

variables = f"{myinst.public} - {myinst._private} - {myinst._MyClass__hidden}"
print(variables)

```

prints  3 - 2 - 1  but is this the expected behaviour, i thought i was protected

Am i doing this right ?

thanks

**Comment by sundarnagarajan** [comment]
Your test code looks ok, and should work to raise an exception as you
expected.

I am traveling, and dealing with a personal emergency, and likely wont get
a chance to debug for a couple of weeks. Sorry.

**Comment by sundarnagarajan** [comment]
As a quick test, you could try wrapping your instance with private()
instead of protect(). Both should work the same for your current test code
but private() wrapper is simpler code path (inside protected_class module).

**Comment by sundarnagarajan** [comment]
nceOK, I did get a few mins to look at your example, and unfortunately,
your test case has a problem.

The protection of attributes is on the WRAPPED object and not on the
ORIGINAL instance.

So in your example:
This line:

variables = f"{myinst.public} - {myinst._private} - {myinst._MyClass__hidden}"


Should be:

variables = f"{wrapped.public} - {wrapped._private} -
{wrapped._MyClass__hidden}"


This will produce an exception as expected.

**Comment by sundarnagarajan** [comment]
Closing this issue - please see my explanation above.
